###
POST http://localhost:8080/city
Content-Type: application/json

{
   "name": "Moscow"
}

<> 2021-06-14T214500.400.txt

###
GET http://localhost:8080/city/1

<> 2021-06-14T214527.200.json

###
DELETE http://localhost:8080/city/1